---
title       : Creating A Sampling Distribution by Simulation
subtitle    : Statistics for a General Audience
author      : Michael Jackson
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [mathjax]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Statistics For A General Audience(?)

* Ensuring an adequate sample size is important if findings are to be reliable
* But how do you explain to a general audience why a certain minimum sample size is important?
* You could try this, which is the statistical formula derived from the Central Lmit Theorem

###### Required Sample Size = $\frac{\frac{z^2p(1-p)}{e^2}}{1+(\frac{z^2p(1-p)}{e^2N})}$

* But you are unlikely to convince any of your audience!
* There has to be a better way to demonstrate why a particular minimum sample size is needed


--- 

## John Rauser Keynote - Strata + Hadoop 2014

* While wrestling with this problem I saw John Rauser's keynote 
* He showed how to demonstrate by simulation rather than theory a "t-test"
    + Check it out at https://www.youtube.com/watch?v=5Dnw46eC-0o
* John's approach let me to consider how I could do the same for determining minimum sample sizes...
* `...` not using theory but by creating a sampling distribution by simulation

--- 

## A Simulated Sampling Distribution

By using a sampling distribution created by taking a large number of different samples from a population we can demonstrate empirically what proportion of those samples are within a certain range, and show that the larger the sample size, the narrower variance from the mean of the sampling distribution. 

```{r, echo=FALSE, fig.width = 13, fig.height = 5}
library(ggplot2)
library(dplyr)

set.seed(4444)

dist <- rbinom(400, 200, prob = 0.5)
dist <- data.frame(dist)
dist$dist <- dist$dist/200*100
dist <- arrange(dist, dist)
dist95 <- dist[11:390, ]
dist_out <- (filter(dist, !(dist %in% dist95)))
dist_out <- unlist(dist_out$dist)


dist$highlight <- ifelse(dist$dist %in% dist_out, "highlight", "normal")
mycolours <- c("highlight" = "red", "normal" = "grey50")

mind <- min(dist95)
maxd <- max(dist95)
m <- mean(dist$dist)

g1<- ggplot(dist, aes(x = dist)) +
  geom_dotplot(method = "histodot", binwidth = 0.5, dotsize = 0.4, fill = "Green") +
 scale_y_continuous(breaks=NULL)+
  theme(axis.title.y=element_blank())
print(g1)




```


--- 

## Slide 4




--- 




